//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angular_with_ajax_vechicle_registarion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking3
    {
        public int vid { get; set; }
        public Nullable<int> reservationid { get; set; }
        public string fromdate { get; set; }
        public string todate { get; set; }
    }
}
