//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angular_with_ajax_vechicle_registarion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class custom2
    {
        public int Id { get; set; }
        public string vtype { get; set; }
        public string owner { get; set; }
        public string date { get; set; }
    }
}
