//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace angular_with_ajax_vechicle_registarion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vechicle
    {
        public int vid { get; set; }
        public string vtype { get; set; }
        public string vbrand { get; set; }
        public string vowner { get; set; }
        public string imagepath { get; set; }
        public string date { get; set; }
        public List<brand> getallbrand;
    }
}
